### ISSUE TITLE
Add feedback disclaimer

### ISSUE THREAD

**Issue by snekiam** [calpoly-csai/swanton-chat-bot#11]
Add some sort of text that says "please send comments and feedback to swantonpoppycp@gmail.com?" or something along those lines.

**Comment by masonmcelvain** [comment]
<img width="704" alt="Screen Shot 2021-01-10 at 1 23 23 PM" src="https://user-images.githubusercontent.com/52104630/104135819-2ac0e480-5347-11eb-9c4e-8dec32665298.png">
We could put this information at the bottom of the suggestions page. This could help avoid clutter on the main page, and I imagine the help button might be an intuitive place to click if people were looking for contact information.

**Comment by Jason-Ku** [comment]
Miles and I can bring up your suggestion with Jeanine and see what she thinks about it! I also agree but we'll have to run it by her first

Jeanine gave the green light on your suggestion Mason! 👍 

I'll implement this soon.
