### ISSUE TITLE
Update Website title and favicon

### ISSUE THREAD

**Issue by snekiam** [calpoly-csai/swanton-chat-bot#6]
Change 'React App' in the tab title to 'Poppy Chat'.

We've also got this logo from Jeanine; I'm not sure how images need to be formatted to be the favicon, but if we need something different let me know.
![thumbnail_Poppy](https://user-images.githubusercontent.com/8095061/104110814-2980b080-5290-11eb-95a1-80eb2710becf.jpg)

**Comment by Jason-Ku** [comment]
![Screen Shot 2021-01-04 at 12 54 36 PM](https://user-images.githubusercontent.com/13087024/104135795-0533db00-5347-11eb-9e8f-f19478cf699f.png)

**Comment by Jason-Ku** [comment]
Commenting for visibility for anyone who looks at this:

Favicons can realistically be any popular image file type (jpg, png, gif, ico <- most popular for favicons, I think), but it just needs to be a small size (16x16 or 32x32)
