### ISSUE TITLE
Thumbs Up / Thumbs Down for answers

### ISSUE THREAD

**Issue by snekiam** [calpoly-csai/swanton-chat-bot#7]
The backend for this needs work still, but we'd like to add the ability for users to give positive/negative sentiment for each answer. From the frontend's perspective, I think this will basically be a POST to swantonpoppy.org/*some_endpoint*, with the question, the given answer, and whether the user is giving a thumbs-up or a thumbs-down. Feel free to pick an endpoint name if you have any ideas.

**Comment by Waidhoferj** [comment]
@snekiam I actually have a branch with this implemented. Lmk when you have the backend set up and we'll merge it.

**Comment by snekiam** [comment]
We've got the logic for the backend written, its just not written as an API yet (not integrated with flask yet). This shouldn't be a hard change, I'm a little busy right now but should have something soon.

**Comment by snekiam** [comment]
I finally got around to opening a [pull request](https://github.com/calpoly-csai/swanton/pull/43) for the backend to support this @Waidhoferj. Let me know if this aligns with what you've got or not; I can definitely adjust what the backend receives from the frontend. Right now, a request to the API would look like this in cURL:

```
curl --location --request POST 'https://swantonpoppy.org/log/query' \
--header 'Content-Type: application/json' \
--data-raw '{"question": "Where is swanton?", "answer": "California I think", "sentiment": "negative"}'
```

**Comment by snekiam** [comment]
The API is now up on GCP - the above POST request will return "Success" when it is successful, "Request was missing a required parameter", or "Failed to log the query" (All with appropriate HTTP responses).
