### ISSUE TITLE
Update Chat Title

### ISSUE THREAD

**Issue by snekiam** [calpoly-csai/swanton-chat-bot#8]
Jeanine wants the top of the page to read "Swanton Pacific Ranch Chat" in one text area, rather than one that reads "Swanton" on the top left, and one that reads "Chat" in the middle. Not sure if she wants this in the middle, or on the left, but I think it should replace the current two.

**Comment by Jason-Ku** [comment]
![Uploading thumbnail_SwantonPoppyChatWelcomeInterface_1.png…]()

**Comment by Jason-Ku** [comment]
![thumbnail_SwantonPoppyChatWelcomeInterface_1](https://user-images.githubusercontent.com/13087024/104135731-bede7c00-5346-11eb-829f-84d5cae2d5d2.png)

**Comment by Jason-Ku** [comment]
Looks like this change is already made
